project_id = "emfijlgxorugiuvykszg"

[functions.match-contractors]
verify_jwt = true

[functions.purchase-lead]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
